sudo: false
services:
- docker
language: bash
before_install:
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_e58dbf8351c6_key -iv $encrypted_e58dbf8351c6_iv
  -in ${TRAVIS_BUILD_DIR}/travis/environment-operator-deploykey.enc -out ~/.ssh/travis_rsa
  -d
- chmod 600 ~/.ssh/travis_rsa
- ssh-add ~/.ssh/travis_rsa
install:
- "${TRAVIS_BUILD_DIR}/travis/releaseVersioning.sh"
before_script:
- "${TRAVIS_BUILD_DIR}/travis/unittest.sh"
script:
- "${TRAVIS_BUILD_DIR}/travis/build.sh"
after_success:
- "${TRAVIS_BUILD_DIR}/travis/releaseTagging.sh"
branches:
  only:
  - dev
  - master
env:
  global:
    secure: kx4trtcFBt6Qz4tN8PApGqtvSgoHxwYCkOx/rnEHTQ1yh2B7rhuOVOvlZ0tb1Lqvfn/m53YWgXLci96c9sVYk27BN6p4A8LjATpEcJxnHPSoD3OblXNLObTpI7SqVbJuv1kI5bTW3Xj4O3JbeK2a5VBMMn9oeViMj3v2mJDRoxklSEsA1fwZJLIZ+0BypV5hzT+U+B4PecwXQJEX5Ph9qSHH60wCeVszX1dhDM9QhKrRf+XRIxVOuU/NaaWFBw6aFNR4/0yAEIutuYaQEI1fxVjf9doHzkgWy77lovoxvvH/oCex/svKfu4rtUPMADVcuzMYwg54dUgQrOxHx8wol2e2GhNSK/ssVQD8Owz7Dq1/EP5YXtxBOPxqvqmND+/0SbUmTKmKY+Bnk5xKTPITWzKdYgV+4njW3DzXK/r6SVFvqBPxRE6dnGDqitIHaDIa9Rl29hAUiStl11hWQD/5d9U1ft646D4JmVDZz7Wgx7XuMT0B9I8+bHZT2TTpLw8aRH6+wZjuG7gJDG2BDNYBWrtry04bW3Ht8/h2kVyAFgezfruwIhixw6VQqg5znl4vYOg5Iv/kq11PkPW/T3q3aXNxtVOOqFejklpLbtbm8BJjFTFp0Zlu2MgcJlU92vFssegjcUYho2Wp8iHSUDcYSqX4SCM3oaDWYTE8NthNXUo=
notifications:
  slack:
    rooms:
      - pearsoncloudplatforms:A2p7To7Ih6eh3Xv7jTGkHdHQ#build-bitesize